<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>测试套件</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="http://apps.bdimg.com/libs/Chart.js/0.2.0/Chart.min.js"></script>

    
<style type="text/css" media="screen">
body        { font-family: verdana, arial, helvetica, sans-serif; font-size: 80%; }
table       { font-size: 100%; }
pre         {  }

/* -- heading ---------------------------------------------------------------------- */
h1 {
	font-size: 16pt;
	color: gray;
}
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
	margin-left: 10px;
}

.heading .attribute {
    margin-top: 1ex;
    margin-bottom: 0;
}

.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}

/* -- css div popup ------------------------------------------------------------------------ */
a.popup_link {
}

a.popup_link:hover {
    color: red;
}

.popup_window {
    display: none;
    position: relative;
    left: 0px;
    top: 0px;
    /*border: solid #627173 1px; */
    font-family: "Lucida Console", "Courier New", Courier, monospace;
    text-align: left;
    font-size: 8pt;
    width: 500px;
}

}
/* -- report ------------------------------------------------------------------------ */
#show_detail_line {
    margin-top: 3ex;
    margin-bottom: 1ex;
    margin-left: 10px;
}
#result_table {
    width: 80%;
    border-collapse: collapse;
    border: 1px solid #777;
    margin-left: 10px;
}
#header_row {
    font-weight: bold;
    color: #606060;
    background-color: #f5f5f5;
    border-top-width: 10px;
    border-color: #d6e9c6;
	font-size: 12px;
}
#result_table td {
    border: 1px solid #f5f5f5;
    padding: 2px;

}
#total_row  { font-weight: bold; }
.passClass  { background-color: #d6e9c6; }
.failClass  { background-color: #faebcc; }
.errorClass { background-color: #ebccd1; }
.passCase   { color: #6c6; }
.failCase   { color: #c60; font-weight: bold; }
.errorCase  { color: #c00; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }


/* -- ending ---------------------------------------------------------------------- */
#ending {
}

/* -- chars ---------------------------------------------------------------------- */
.testChars {margin-left: 150px;}

.btn-info1 {
    color: #fff;
    background-color: #d6e9c6;
    border-color: #d6e9c6;
}

.btn-info2 {
    color: #fff;
    background-color: #faebcc;
    border-color: #faebcc;
}

.btn-info3 {
    color: #fff;
    background-color: #ebccd1;
    border-color: #ebccd1;
}
</style>

</head>
<body>
<script language="javascript" type="text/javascript"><!--
output_list = Array();

/* level - 0:Summary; 1:Failed; 2:All */
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level < 1) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level > 1) {
                tr.className = '';
            }
            else {
                tr.className = 'hiddenRow';
            }
        }
    }
}


function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        tid0 = 't' + cid.substr(1) + '.' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        if (toHide) {
            document.getElementById('div_'+tid).style.display = 'none'
            document.getElementById(tid).className = 'hiddenRow';
        }
        else {
            document.getElementById(tid).className = '';
        }
    }
}


function showTestDetail(div_id){
    var details_div = document.getElementById(div_id)
    var displayState = details_div.style.display
    // alert(displayState)
    if (displayState != 'block' ) {
        displayState = 'block'
        details_div.style.display = 'block'
    }
    else {
        details_div.style.display = 'none'
    }
}


function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}

/* obsoleted by detail in <div>
function showOutput(id, name) {
    var w = window.open("", //url
                    name,
                    "resizable,scrollbars,status,width=800,height=450");
    d = w.document;
    d.write("<pre>");
    d.write(html_escape(output_list[id]));
    d.write("\n");
    d.write("<a href='javascript:window.close()'>close</a>\n");
    d.write("</pre>\n");
    d.close();
}
*/
--></script>

<div class='heading'>
<h1>测试套件</h1>
<p class='attribute'><strong>Start Time:</strong> 2021-12-23 15:25:48</p>
<p class='attribute'><strong>Duration:</strong> 0:01:21.756625</p>
<p class='attribute'><strong>Status:</strong> Error 1</p>

<p class='description'>收集测试报告</p>
</div>

<div style="float:left; margin-left: 10px;">
	<p> Test Case Pie charts </p>
	<a class="btn btn-xs btn-info1">-Pass-</a><br>
	<a class="btn btn-xs btn-info2">-Faild-</a><br>
	<a class="btn btn-xs btn-info3">-Error-</a><br>
</div>

<div class="testChars">
	<canvas id="myChart" width="250" height="250"></canvas>
</div>



<p id='show_detail_line' style="margin-left: 10px;">Show
<a href='javascript:showCase(0)' class="btn btn-xs btn-primary">Summary</a>
<a href='javascript:showCase(1)' class="btn btn-xs btn-danger">Failed</a>
<a href='javascript:showCase(2)' class="btn btn-xs btn-info">All</a>
</p>
<table id='result_table'>
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="panel-title">
    <td>Test Group/Test case</td>
    <td>Count</td>
    <td>Pass</td>
    <td>Fail</td>
    <td>Error</td>
    <td>View</td>
</tr>

<tr class='errorClass'>
    <td>testSuite.modouLoginSuite.MoDouLogin</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c1',1)">Detail</a></td>
</tr>

<tr id='ft1.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_case_01</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.1')" >
        error</a>

    <div id='div_ft1.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.1: --- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 72, in emit
    self.doRollover()
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 396, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 113, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\86133\\.PyCharmCE2017.2\\modou\\logger\\2021-12-23.log' -&gt; 'C:\\Users\\86133\\.PyCharmCE2017.2\\modou\\logger\\2021-12-23.log.2021-12-23_12'
Call stack:
  File "&lt;string&gt;", line 1, in &lt;module&gt;
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 118, in _main
    return self._bootstrap()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\run\runModou.py", line 34, in runnerCaseApp
    runner.start_run(suite)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseReport.py", line 35, in start_run
    runner.run(suite)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\htmlTestRunner.py", line 699, in run
    test(result)
  File "C:\Program Files\Python36\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Python36\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\Python36\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Python36\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\86133\.PyCharmCE2017.2\modou\testSuite\modouLoginSuite.py", line 40, in test_case_01
    self.login.login_page('19900000001','123456')
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 83, in login_page
    self.click_positive()
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 20, in click_positive
    self.driver.click(self.source.get_value('modouPage.ini','Button','首次同意'))
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseOperate.py", line 118, in click
    el = self.get_element(css)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseOperate.py", line 45, in get_element
    "by %s via value: %s " % (element.text, ele_type, value))
Message: "Had find the element '  ' successful by id via value: com.wantong.yijian:id/tv_positive "
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 72, in emit
    self.doRollover()
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 396, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 113, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\86133\\.PyCharmCE2017.2\\modou\\logger\\2021-12-23.log' -&gt; 'C:\\Users\\86133\\.PyCharmCE2017.2\\modou\\logger\\2021-12-23.log.2021-12-23_12'
Call stack:
  File "&lt;string&gt;", line 1, in &lt;module&gt;
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 118, in _main
    return self._bootstrap()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\run\runModou.py", line 34, in runnerCaseApp
    runner.start_run(suite)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseReport.py", line 35, in start_run
    runner.run(suite)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\htmlTestRunner.py", line 699, in run
    test(result)
  File "C:\Program Files\Python36\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Python36\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\Python36\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Python36\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\86133\.PyCharmCE2017.2\modou\testSuite\modouLoginSuite.py", line 40, in test_case_01
    self.login.login_page('19900000001','123456')
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 83, in login_page
    self.click_positive()
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 20, in click_positive
    self.driver.click(self.source.get_value('modouPage.ini','Button','首次同意'))
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseOperate.py", line 120, in click
    logger.info("click element css")
Message: 'click element css'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 72, in emit
    self.doRollover()
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 396, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 113, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\86133\\.PyCharmCE2017.2\\modou\\logger\\2021-12-23.log' -&gt; 'C:\\Users\\86133\\.PyCharmCE2017.2\\modou\\logger\\2021-12-23.log.2021-12-23_12'
Call stack:
  File "&lt;string&gt;", line 1, in &lt;module&gt;
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 118, in _main
    return self._bootstrap()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\run\runModou.py", line 34, in runnerCaseApp
    runner.start_run(suite)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseReport.py", line 35, in start_run
    runner.run(suite)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\htmlTestRunner.py", line 699, in run
    test(result)
  File "C:\Program Files\Python36\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Python36\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\Python36\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Python36\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\86133\.PyCharmCE2017.2\modou\testSuite\modouLoginSuite.py", line 40, in test_case_01
    self.login.login_page('19900000001','123456')
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 84, in login_page
    self.click_xiaomiallow()
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 30, in click_xiaomiallow
    self.driver.click(self.source.get_value('modouPage.ini','Button','小米媒体权限同意'))
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseOperate.py", line 118, in click
    el = self.get_element(css)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseOperate.py", line 45, in get_element
    "by %s via value: %s " % (element.text, ele_type, value))
Message: "Had find the element ' 允许 ' successful by id via value: android:id/button1 "
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 72, in emit
    self.doRollover()
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 396, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 113, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\86133\\.PyCharmCE2017.2\\modou\\logger\\2021-12-23.log' -&gt; 'C:\\Users\\86133\\.PyCharmCE2017.2\\modou\\logger\\2021-12-23.log.2021-12-23_12'
Call stack:
  File "&lt;string&gt;", line 1, in &lt;module&gt;
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 118, in _main
    return self._bootstrap()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\run\runModou.py", line 34, in runnerCaseApp
    runner.start_run(suite)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseReport.py", line 35, in start_run
    runner.run(suite)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\htmlTestRunner.py", line 699, in run
    test(result)
  File "C:\Program Files\Python36\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Python36\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\Python36\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Python36\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\86133\.PyCharmCE2017.2\modou\testSuite\modouLoginSuite.py", line 40, in test_case_01
    self.login.login_page('19900000001','123456')
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 84, in login_page
    self.click_xiaomiallow()
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 30, in click_xiaomiallow
    self.driver.click(self.source.get_value('modouPage.ini','Button','小米媒体权限同意'))
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseOperate.py", line 120, in click
    logger.info("click element css")
Message: 'click element css'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 72, in emit
    self.doRollover()
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 396, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 113, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\86133\\.PyCharmCE2017.2\\modou\\logger\\2021-12-23.log' -&gt; 'C:\\Users\\86133\\.PyCharmCE2017.2\\modou\\logger\\2021-12-23.log.2021-12-23_12'
Call stack:
  File "&lt;string&gt;", line 1, in &lt;module&gt;
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 118, in _main
    return self._bootstrap()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\run\runModou.py", line 34, in runnerCaseApp
    runner.start_run(suite)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseReport.py", line 35, in start_run
    runner.run(suite)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\htmlTestRunner.py", line 699, in run
    test(result)
  File "C:\Program Files\Python36\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Python36\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\Python36\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Python36\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\86133\.PyCharmCE2017.2\modou\testSuite\modouLoginSuite.py", line 40, in test_case_01
    self.login.login_page('19900000001','123456')
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 86, in login_page
    self.click_my()
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 36, in click_my
    self.driver.click(self.source.get_value('modouPage.ini','Button','我的'))
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseOperate.py", line 118, in click
    el = self.get_element(css)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseOperate.py", line 45, in get_element
    "by %s via value: %s " % (element.text, ele_type, value))
Message: "Had find the element '  ' successful by id via value: com.wantong.yijian:id/tab3 "
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 72, in emit
    self.doRollover()
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 396, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 113, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\86133\\.PyCharmCE2017.2\\modou\\logger\\2021-12-23.log' -&gt; 'C:\\Users\\86133\\.PyCharmCE2017.2\\modou\\logger\\2021-12-23.log.2021-12-23_12'
Call stack:
  File "&lt;string&gt;", line 1, in &lt;module&gt;
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 118, in _main
    return self._bootstrap()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\run\runModou.py", line 34, in runnerCaseApp
    runner.start_run(suite)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseReport.py", line 35, in start_run
    runner.run(suite)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\htmlTestRunner.py", line 699, in run
    test(result)
  File "C:\Program Files\Python36\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Python36\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\Python36\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Python36\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\86133\.PyCharmCE2017.2\modou\testSuite\modouLoginSuite.py", line 40, in test_case_01
    self.login.login_page('19900000001','123456')
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 86, in login_page
    self.click_my()
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 36, in click_my
    self.driver.click(self.source.get_value('modouPage.ini','Button','我的'))
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseOperate.py", line 120, in click
    logger.info("click element css")
Message: 'click element css'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 72, in emit
    self.doRollover()
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 396, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 113, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\86133\\.PyCharmCE2017.2\\modou\\logger\\2021-12-23.log' -&gt; 'C:\\Users\\86133\\.PyCharmCE2017.2\\modou\\logger\\2021-12-23.log.2021-12-23_12'
Call stack:
  File "&lt;string&gt;", line 1, in &lt;module&gt;
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 118, in _main
    return self._bootstrap()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\run\runModou.py", line 34, in runnerCaseApp
    runner.start_run(suite)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseReport.py", line 35, in start_run
    runner.run(suite)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\htmlTestRunner.py", line 699, in run
    test(result)
  File "C:\Program Files\Python36\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Python36\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\Python36\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Python36\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\86133\.PyCharmCE2017.2\modou\testSuite\modouLoginSuite.py", line 40, in test_case_01
    self.login.login_page('19900000001','123456')
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 87, in login_page
    self.click_clklogin()
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 41, in click_clklogin
    self.driver.click(self.source.get_value('modouPage.ini','Button','点击登录'))
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseOperate.py", line 118, in click
    el = self.get_element(css)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseOperate.py", line 87, in get_element
    "by %s via value: %s " % (element.text, ele_type, value))
Message: "Had find the element ' 请点击登录 ' successful by xpath via value: //android.widget.TextView[@text='请点击登录'] "
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 72, in emit
    self.doRollover()
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 396, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 113, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\86133\\.PyCharmCE2017.2\\modou\\logger\\2021-12-23.log' -&gt; 'C:\\Users\\86133\\.PyCharmCE2017.2\\modou\\logger\\2021-12-23.log.2021-12-23_12'
Call stack:
  File "&lt;string&gt;", line 1, in &lt;module&gt;
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 118, in _main
    return self._bootstrap()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\run\runModou.py", line 34, in runnerCaseApp
    runner.start_run(suite)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseReport.py", line 35, in start_run
    runner.run(suite)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\htmlTestRunner.py", line 699, in run
    test(result)
  File "C:\Program Files\Python36\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Python36\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\Python36\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Python36\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\86133\.PyCharmCE2017.2\modou\testSuite\modouLoginSuite.py", line 40, in test_case_01
    self.login.login_page('19900000001','123456')
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 87, in login_page
    self.click_clklogin()
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 41, in click_clklogin
    self.driver.click(self.source.get_value('modouPage.ini','Button','点击登录'))
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseOperate.py", line 120, in click
    logger.info("click element css")
Message: 'click element css'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 72, in emit
    self.doRollover()
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 396, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 113, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\86133\\.PyCharmCE2017.2\\modou\\logger\\2021-12-23.log' -&gt; 'C:\\Users\\86133\\.PyCharmCE2017.2\\modou\\logger\\2021-12-23.log.2021-12-23_12'
Call stack:
  File "&lt;string&gt;", line 1, in &lt;module&gt;
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 118, in _main
    return self._bootstrap()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\run\runModou.py", line 34, in runnerCaseApp
    runner.start_run(suite)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseReport.py", line 35, in start_run
    runner.run(suite)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\htmlTestRunner.py", line 699, in run
    test(result)
  File "C:\Program Files\Python36\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Python36\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\Python36\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Python36\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\86133\.PyCharmCE2017.2\modou\testSuite\modouLoginSuite.py", line 40, in test_case_01
    self.login.login_page('19900000001','123456')
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 88, in login_page
    self.input_username(username)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 47, in input_username
    self.driver.type(self.source.get_value('modouPage.ini','TextInput','账号'),username)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseOperate.py", line 246, in type
    el = self.get_element(css)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseOperate.py", line 45, in get_element
    "by %s via value: %s " % (element.text, ele_type, value))
Message: "Had find the element ' 请输入您的手机号 ' successful by id via value: com.wantong.yijian:id/et_phone "
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 72, in emit
    self.doRollover()
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 396, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 113, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\86133\\.PyCharmCE2017.2\\modou\\logger\\2021-12-23.log' -&gt; 'C:\\Users\\86133\\.PyCharmCE2017.2\\modou\\logger\\2021-12-23.log.2021-12-23_12'
Call stack:
  File "&lt;string&gt;", line 1, in &lt;module&gt;
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 118, in _main
    return self._bootstrap()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\run\runModou.py", line 34, in runnerCaseApp
    runner.start_run(suite)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseReport.py", line 35, in start_run
    runner.run(suite)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\htmlTestRunner.py", line 699, in run
    test(result)
  File "C:\Program Files\Python36\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Python36\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\Python36\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Python36\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\86133\.PyCharmCE2017.2\modou\testSuite\modouLoginSuite.py", line 40, in test_case_01
    self.login.login_page('19900000001','123456')
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 88, in login_page
    self.input_username(username)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 47, in input_username
    self.driver.type(self.source.get_value('modouPage.ini','TextInput','账号'),username)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseOperate.py", line 249, in type
    logger.info(" Input text %s to %s element." % (text, css))
Message: ' Input text 19900000001 to id=&gt;com.wantong.yijian:id/et_phone element.'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 72, in emit
    self.doRollover()
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 396, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 113, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\86133\\.PyCharmCE2017.2\\modou\\logger\\2021-12-23.log' -&gt; 'C:\\Users\\86133\\.PyCharmCE2017.2\\modou\\logger\\2021-12-23.log.2021-12-23_12'
Call stack:
  File "&lt;string&gt;", line 1, in &lt;module&gt;
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 118, in _main
    return self._bootstrap()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\run\runModou.py", line 34, in runnerCaseApp
    runner.start_run(suite)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseReport.py", line 35, in start_run
    runner.run(suite)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\htmlTestRunner.py", line 699, in run
    test(result)
  File "C:\Program Files\Python36\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Python36\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\Python36\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Python36\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\86133\.PyCharmCE2017.2\modou\testSuite\modouLoginSuite.py", line 40, in test_case_01
    self.login.login_page('19900000001','123456')
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 89, in login_page
    self.input_password(password)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 52, in input_password
    self.driver.type(self.source.get_value('modouPage.ini', 'TextInput', '验证码'), password)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseOperate.py", line 246, in type
    el = self.get_element(css)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseOperate.py", line 45, in get_element
    "by %s via value: %s " % (element.text, ele_type, value))
Message: "Had find the element ' 请输入收到的验证码 ' successful by id via value: com.wantong.yijian:id/et_code "
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 72, in emit
    self.doRollover()
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 396, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "C:\Program Files\Python36\lib\logging\handlers.py", line 113, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\86133\\.PyCharmCE2017.2\\modou\\logger\\2021-12-23.log' -&gt; 'C:\\Users\\86133\\.PyCharmCE2017.2\\modou\\logger\\2021-12-23.log.2021-12-23_12'
Call stack:
  File "&lt;string&gt;", line 1, in &lt;module&gt;
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 118, in _main
    return self._bootstrap()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\run\runModou.py", line 34, in runnerCaseApp
    runner.start_run(suite)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseReport.py", line 35, in start_run
    runner.run(suite)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\htmlTestRunner.py", line 699, in run
    test(result)
  File "C:\Program Files\Python36\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Python36\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\Python36\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Python36\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\86133\.PyCharmCE2017.2\modou\testSuite\modouLoginSuite.py", line 40, in test_case_01
    self.login.login_page('19900000001','123456')
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 89, in login_page
    self.input_password(password)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 52, in input_password
    self.driver.type(self.source.get_value('modouPage.ini', 'TextInput', '验证码'), password)
  File "C:\Users\86133\.PyCharmCE2017.2\modou\mobileUtil\baseOperate.py", line 249, in type
    logger.info(" Input text %s to %s element." % (text, css))
Message: ' Input text 123456 to id=&gt;com.wantong.yijian:id/et_code element.'
Arguments: ()
Traceback (most recent call last):
  File "C:\Users\86133\.PyCharmCE2017.2\modou\testSuite\modouLoginSuite.py", line 40, in test_case_01
    self.login.login_page('19900000001','123456')
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 90, in login_page
    self.click_agree()
  File "C:\Users\86133\.PyCharmCE2017.2\modou\page\loginModou.py", line 57, in click_agree
    self.driver.type(self.source.get_value('modouPage.ini','Button','同意协议'))
TypeError: type() missing 1 required positional argument: 'text'


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='total_row'>
    <td>Total</td>
    <td>1</td>
    <td class="text text-success">0</td>
    <td class="text text-danger">0</td>
    <td class="text text-warning">1</td>
    <td>&nbsp;</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>

    <script type="text/javascript">
var data = [
	{
		value: 1,
		color: "#ebccd1",
		label: "Error",
		labelColor: 'white',
		labelFontSize: '16'
	},
	{
		value : 0,
		color : "#faebcc",
		label: "Fail",
		labelColor: 'white',
		labelFontSize: '16'
	},
	{
		value : 0,
		color : "#d6e9c6",
		label : "Pass",
		labelColor: 'white',
		labelFontSize: '16'
	}			
]

var newopts = {
     animationSteps: 100,
 		animationEasing: 'easeInOutQuart',
}

//Get the context of the canvas element we want to select
var ctx = document.getElementById("myChart").getContext("2d");

var myNewChart = new Chart(ctx).Pie(data,newopts);

</script>
	
</body>
</html>
